import { Component } from '@angular/core';

@Component({
  selector: 'app-career',
  templateUrl: './career.component.html',
  styleUrls: ['./career.component.scss']
})
export class CareerComponent {
  careers = [
    {
      id: 1,
      title: 'First',
      salary: 300000,
      type: 'Full-time',
      description: 'Lorem ipsum dolor sit amet consectetur. Aliquam amet mollis congue viverra egestas in. Vulputate aliquet accumsan mollis id. Mauris praesent adipiscing volutpat dolor. Proin nisl nisl facilisis arcu nunc faucibus laoreet. Ut magnis tellus sagittis elementum. Nunc tempus scelerisque netus urna scelerisque elementum accumsan. Laoreet feugiat aliquam lectus proin a mattis. Viverra proin lacus tristique egestas tempus scelerisque auctor at fusce. Fermentum ligula dictumst morbi natoque tristique et purus lectus. Commodo interdum sodales pellentesque aenean aliquet. Egestas id urna purus tellus ut eu. Blandit vitae morbi pulvinar nisl. A magna aliquet lacus id massa lectus tincidunt sagittis. Volutpat dui vel laoreet nunc habitasse convallis nibh lectus cursus. Sit sit sit mi elit rhoncus accumsan id in metus. Quam aliquam id auctor phasellus dolor a enim. Viverra ac mi at sem lectus etiam orci dui leo. Nulla orci vitae vel nibh. Consequat ac nunc elit in pellentesque tristique in. Accumsan morbi dolor lacus vestibulum molestie arcu erat dictumst cursus. Porttitor ullamcorper pellentesque augue et diam. Urna hac ut suspendisse eleifend adipiscing adipiscing at massa commodo. Leo viverra elementum leo non nullam dolor arcu. Tristique aliquam massa sapien sed felis volutpat nisi sit. Sed habitant ac facilisis eros nibh. Lorem ipsum dolor sit amet consectetur. Aliquam amet mollis congue viverra egestas in. Vulputate aliquet accumsan mollis id. Mauris praesent adipiscing volutpat dolor. Proin nisl nisl facilisis arcu nunc faucibus laoreet. Ut magnis tellus sagittis elementum. Nunc tempus scelerisque netus urna scelerisque elementum accumsan. Laoreet feugiat aliquam lectus proin a mattis. Viverra proin lacus tristique egestas tempus scelerisque auctor at fusce. Fermentum ligula dictumst morbi natoque tristique et purus lectus. Commodo interdum sodales pellentesque aenean aliquet. Egestas id urna purus tellus ut eu. Blandit vitae morbi pulvinar nisl. A magna aliquet lacus id massa lectus tincidunt sagittis. Volutpat dui vel laoreet nunc habitasse convallis nibh lectus cursus. Sit sit sit mi elit rhoncus accumsan id in metus. Quam aliquam id auctor phasellus dolor a enim. Viverra ac mi at sem lectus etiam orci dui leo. Nulla orci vitae vel nibh. Consequat ac nunc elit in pellentesque tristique in. Accumsan morbi dolor lacus vestibulum molestie arcu erat dictumst cursus. Porttitor ullamcorper pellentesque augue et diam. Urna hac ut suspendisse eleifend adipiscing adipiscing at massa commodo. Leo viverra elementum leo non nullam dolor arcu. Tristique aliquam massa sapien sed felis volutpat nisi sit. Sed habitant ac facilisis eros nibh.'
    },
    {
      id: 2,
      title: 'Second',
      salary: 200000,
      type: 'Part-time',
      description: 'Lorem ipsum dolor sit amet consectetur. Aliquam amet mollis congue viverra egestas in. Vulputate aliquet accumsan mollis id. Mauris praesent adipiscing volutpat dolor. Proin nisl nisl facilisis arcu nunc faucibus laoreet. Ut magnis tellus sagittis elementum. Nunc tempus scelerisque netus urna scelerisque elementum accumsan. Laoreet feugiat aliquam lectus proin a mattis. Viverra proin lacus tristique egestas tempus scelerisque auctor at fusce. Fermentum ligula dictumst morbi natoque tristique et purus lectus. Commodo interdum sodales pellentesque aenean aliquet. Egestas id urna purus tellus ut eu. Blandit vitae morbi pulvinar nisl. A magna aliquet lacus id massa lectus tincidunt sagittis. Volutpat dui vel laoreet nunc habitasse convallis nibh lectus cursus. Sit sit sit mi elit rhoncus accumsan id in metus. Quam aliquam id auctor phasellus dolor a enim. Viverra ac mi at sem lectus etiam orci dui leo. Nulla orci vitae vel nibh. Consequat ac nunc elit in pellentesque tristique in. Accumsan morbi dolor lacus vestibulum molestie arcu erat dictumst cursus. Porttitor ullamcorper pellentesque augue et diam. Urna hac ut suspendisse eleifend adipiscing adipiscing at massa commodo. Leo viverra elementum leo non nullam dolor arcu. Tristique aliquam massa sapien sed felis volutpat nisi sit. Sed habitant ac facilisis eros nibh. Lorem ipsum dolor sit amet consectetur. Aliquam amet mollis congue viverra egestas in. Vulputate aliquet accumsan mollis id. Mauris praesent adipiscing volutpat dolor. Proin nisl nisl facilisis arcu nunc faucibus laoreet. Ut magnis tellus sagittis elementum. Nunc tempus scelerisque netus urna scelerisque elementum accumsan. Laoreet feugiat aliquam lectus proin a mattis. Viverra proin lacus tristique egestas tempus scelerisque auctor at fusce. Fermentum ligula dictumst morbi natoque tristique et purus lectus. Commodo interdum sodales pellentesque aenean aliquet. Egestas id urna purus tellus ut eu. Blandit vitae morbi pulvinar nisl. A magna aliquet lacus id massa lectus tincidunt sagittis. Volutpat dui vel laoreet nunc habitasse convallis nibh lectus cursus. Sit sit sit mi elit rhoncus accumsan id in metus. Quam aliquam id auctor phasellus dolor a enim. Viverra ac mi at sem lectus etiam orci dui leo. Nulla orci vitae vel nibh. Consequat ac nunc elit in pellentesque tristique in. Accumsan morbi dolor lacus vestibulum molestie arcu erat dictumst cursus. Porttitor ullamcorper pellentesque augue et diam. Urna hac ut suspendisse eleifend adipiscing adipiscing at massa commodo. Leo viverra elementum leo non nullam dolor arcu. Tristique aliquam massa sapien sed felis volutpat nisi sit. Sed habitant ac facilisis eros nibh.'
    },
    {
      id: 3,
      title: 'Third',
      salary: 200000,
      type: 'Contract',
      description: 'Lorem ipsum dolor sit amet consectetur. Aliquam amet mollis congue viverra egestas in. Vulputate aliquet accumsan mollis id. Mauris praesent adipiscing volutpat dolor. Proin nisl nisl facilisis arcu nunc faucibus laoreet. Ut magnis tellus sagittis elementum. Nunc tempus scelerisque netus urna scelerisque elementum accumsan. Laoreet feugiat aliquam lectus proin a mattis. Viverra proin lacus tristique egestas tempus scelerisque auctor at fusce. Fermentum ligula dictumst morbi natoque tristique et purus lectus. Commodo interdum sodales pellentesque aenean aliquet. Egestas id urna purus tellus ut eu. Blandit vitae morbi pulvinar nisl. A magna aliquet lacus id massa lectus tincidunt sagittis. Volutpat dui vel laoreet nunc habitasse convallis nibh lectus cursus. Sit sit sit mi elit rhoncus accumsan id in metus. Quam aliquam id auctor phasellus dolor a enim. Viverra ac mi at sem lectus etiam orci dui leo. Nulla orci vitae vel nibh. Consequat ac nunc elit in pellentesque tristique in. Accumsan morbi dolor lacus vestibulum molestie arcu erat dictumst cursus. Porttitor ullamcorper pellentesque augue et diam. Urna hac ut suspendisse eleifend adipiscing adipiscing at massa commodo. Leo viverra elementum leo non nullam dolor arcu. Tristique aliquam massa sapien sed felis volutpat nisi sit. Sed habitant ac facilisis eros nibh. Lorem ipsum dolor sit amet consectetur. Aliquam amet mollis congue viverra egestas in. Vulputate aliquet accumsan mollis id. Mauris praesent adipiscing volutpat dolor. Proin nisl nisl facilisis arcu nunc faucibus laoreet. Ut magnis tellus sagittis elementum. Nunc tempus scelerisque netus urna scelerisque elementum accumsan. Laoreet feugiat aliquam lectus proin a mattis. Viverra proin lacus tristique egestas tempus scelerisque auctor at fusce. Fermentum ligula dictumst morbi natoque tristique et purus lectus. Commodo interdum sodales pellentesque aenean aliquet. Egestas id urna purus tellus ut eu. Blandit vitae morbi pulvinar nisl. A magna aliquet lacus id massa lectus tincidunt sagittis. Volutpat dui vel laoreet nunc habitasse convallis nibh lectus cursus. Sit sit sit mi elit rhoncus accumsan id in metus. Quam aliquam id auctor phasellus dolor a enim. Viverra ac mi at sem lectus etiam orci dui leo. Nulla orci vitae vel nibh. Consequat ac nunc elit in pellentesque tristique in. Accumsan morbi dolor lacus vestibulum molestie arcu erat dictumst cursus. Porttitor ullamcorper pellentesque augue et diam. Urna hac ut suspendisse eleifend adipiscing adipiscing at massa commodo. Leo viverra elementum leo non nullam dolor arcu. Tristique aliquam massa sapien sed felis volutpat nisi sit. Sed habitant ac facilisis eros nibh.'
    },
    {
      id: 4,
      title: 'Fourth',
      salary: 100000,
      type: 'Internship',
      description: 'Lorem ipsum dolor sit amet consectetur. Aliquam amet mollis congue viverra egestas in. Vulputate aliquet accumsan mollis id. Mauris praesent adipiscing volutpat dolor. Proin nisl nisl facilisis arcu nunc faucibus laoreet. Ut magnis tellus sagittis elementum. Nunc tempus scelerisque netus urna scelerisque elementum accumsan. Laoreet feugiat aliquam lectus proin a mattis. Viverra proin lacus tristique egestas tempus scelerisque auctor at fusce. Fermentum ligula dictumst morbi natoque tristique et purus lectus. Commodo interdum sodales pellentesque aenean aliquet. Egestas id urna purus tellus ut eu. Blandit vitae morbi pulvinar nisl. A magna aliquet lacus id massa lectus tincidunt sagittis. Volutpat dui vel laoreet nunc habitasse convallis nibh lectus cursus. Sit sit sit mi elit rhoncus accumsan id in metus. Quam aliquam id auctor phasellus dolor a enim. Viverra ac mi at sem lectus etiam orci dui leo. Nulla orci vitae vel nibh. Consequat ac nunc elit in pellentesque tristique in. Accumsan morbi dolor lacus vestibulum molestie arcu erat dictumst cursus. Porttitor ullamcorper pellentesque augue et diam. Urna hac ut suspendisse eleifend adipiscing adipiscing at massa commodo. Leo viverra elementum leo non nullam dolor arcu. Tristique aliquam massa sapien sed felis volutpat nisi sit. Sed habitant ac facilisis eros nibh. Lorem ipsum dolor sit amet consectetur. Aliquam amet mollis congue viverra egestas in. Vulputate aliquet accumsan mollis id. Mauris praesent adipiscing volutpat dolor. Proin nisl nisl facilisis arcu nunc faucibus laoreet. Ut magnis tellus sagittis elementum. Nunc tempus scelerisque netus urna scelerisque elementum accumsan. Laoreet feugiat aliquam lectus proin a mattis. Viverra proin lacus tristique egestas tempus scelerisque auctor at fusce. Fermentum ligula dictumst morbi natoque tristique et purus lectus. Commodo interdum sodales pellentesque aenean aliquet. Egestas id urna purus tellus ut eu. Blandit vitae morbi pulvinar nisl. A magna aliquet lacus id massa lectus tincidunt sagittis. Volutpat dui vel laoreet nunc habitasse convallis nibh lectus cursus. Sit sit sit mi elit rhoncus accumsan id in metus. Quam aliquam id auctor phasellus dolor a enim. Viverra ac mi at sem lectus etiam orci dui leo. Nulla orci vitae vel nibh. Consequat ac nunc elit in pellentesque tristique in. Accumsan morbi dolor lacus vestibulum molestie arcu erat dictumst cursus. Porttitor ullamcorper pellentesque augue et diam. Urna hac ut suspendisse eleifend adipiscing adipiscing at massa commodo. Leo viverra elementum leo non nullam dolor arcu. Tristique aliquam massa sapien sed felis volutpat nisi sit. Sed habitant ac facilisis eros nibh.'
    },
    {
      id: 5,
      title: 'Fifth',
      salary: 500000,
      type: 'Full-time',
      description: 'Lorem ipsum dolor sit amet consectetur. Aliquam amet mollis congue viverra egestas in. Vulputate aliquet accumsan mollis id. Mauris praesent adipiscing volutpat dolor. Proin nisl nisl facilisis arcu nunc faucibus laoreet. Ut magnis tellus sagittis elementum. Nunc tempus scelerisque netus urna scelerisque elementum accumsan. Laoreet feugiat aliquam lectus proin a mattis. Viverra proin lacus tristique egestas tempus scelerisque auctor at fusce. Fermentum ligula dictumst morbi natoque tristique et purus lectus. Commodo interdum sodales pellentesque aenean aliquet. Egestas id urna purus tellus ut eu. Blandit vitae morbi pulvinar nisl. A magna aliquet lacus id massa lectus tincidunt sagittis. Volutpat dui vel laoreet nunc habitasse convallis nibh lectus cursus. Sit sit sit mi elit rhoncus accumsan id in metus. Quam aliquam id auctor phasellus dolor a enim. Viverra ac mi at sem lectus etiam orci dui leo. Nulla orci vitae vel nibh. Consequat ac nunc elit in pellentesque tristique in. Accumsan morbi dolor lacus vestibulum molestie arcu erat dictumst cursus. Porttitor ullamcorper pellentesque augue et diam. Urna hac ut suspendisse eleifend adipiscing adipiscing at massa commodo. Leo viverra elementum leo non nullam dolor arcu. Tristique aliquam massa sapien sed felis volutpat nisi sit. Sed habitant ac facilisis eros nibh. Lorem ipsum dolor sit amet consectetur. Aliquam amet mollis congue viverra egestas in. Vulputate aliquet accumsan mollis id. Mauris praesent adipiscing volutpat dolor. Proin nisl nisl facilisis arcu nunc faucibus laoreet. Ut magnis tellus sagittis elementum. Nunc tempus scelerisque netus urna scelerisque elementum accumsan. Laoreet feugiat aliquam lectus proin a mattis. Viverra proin lacus tristique egestas tempus scelerisque auctor at fusce. Fermentum ligula dictumst morbi natoque tristique et purus lectus. Commodo interdum sodales pellentesque aenean aliquet. Egestas id urna purus tellus ut eu. Blandit vitae morbi pulvinar nisl. A magna aliquet lacus id massa lectus tincidunt sagittis. Volutpat dui vel laoreet nunc habitasse convallis nibh lectus cursus. Sit sit sit mi elit rhoncus accumsan id in metus. Quam aliquam id auctor phasellus dolor a enim. Viverra ac mi at sem lectus etiam orci dui leo. Nulla orci vitae vel nibh. Consequat ac nunc elit in pellentesque tristique in. Accumsan morbi dolor lacus vestibulum molestie arcu erat dictumst cursus. Porttitor ullamcorper pellentesque augue et diam. Urna hac ut suspendisse eleifend adipiscing adipiscing at massa commodo. Leo viverra elementum leo non nullam dolor arcu. Tristique aliquam massa sapien sed felis volutpat nisi sit. Sed habitant ac facilisis eros nibh.'
    }
  ]

  currentCareer: any;
  isCareerModal: boolean = false


  // Open Career details
  openCareerDetails(career: any) {
    this.currentCareer = career
    this.isCareerModal = true
    
  } 
  
  // Close Career details
   closeCareerDetails() {
    this.isCareerModal = false
  }
}
